.PHONY: clean All

All:
	@echo "----------Building project:[ lonktados - Debug ]----------"
	@cd "/home/pi/Desktop/lonktados" && "$(MAKE)" -f  "lonktados.mk"
clean:
	@echo "----------Cleaning project:[ lonktados - Debug ]----------"
	@cd "/home/pi/Desktop/lonktados" && "$(MAKE)" -f  "lonktados.mk" clean
